version: "3.7"

services:
  webapp:
    image: docker-registry.apogee-dev.com/host-mgmt
    restart: "always"
    volumes:
      - "/mnt/ssd/projects/private-hosting/host-mgmt/keys:/home/app/keys"
    environment:
      - AppPathPrefix=/hostmgmt
    deploy:
      labels:
        - "traefik.docker.network=functions"
        - "traefik.enable=true"
        - "traefik.http.routers.host-mgmt.rule=Host(`offsite.apogee-dev.com`) && PathPrefix(`/hostmgmt`)"
        - "traefik.http.routers.host-mgmt.entrypoints=web,websecured"
        - "traefik.http.routers.host-mgmt.middlewares=default-compress@file"
        - "traefik.http.routers.host-mgmt.tls.domains[0].main=offsite.apogee-dev.com"
        - "traefik.http.routers.host-mgmt.tls.certResolver=default"
        - "traefik.http.routers.host-mgmt.service=host-mgmt"

        - "traefik.http.services.host-mgmt.loadbalancer.server.port=5000"
        - "traefik.http.services.host-mgmt.loadbalancer.sticky.cookie.httponly=true"
        - "traefik.http.services.host-mgmt.loadbalancer.sticky.cookie.secure=true"

      mode: replicated
      placement:
        constraints:
          - "node.platform.os == linux"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - functions
    logging:
      driver: fluentd
      options:
        tag: "docker.{{.Name}}"
        env: "SERVICE_NAME,DEPLOY_ENV"
        fluentd-address: localhost:24224

networks:
  functions:
    external: true
