services:
  x-base-service:
    restart: unless-stopped
    networks:
      - public-proxy
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 512m
