receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# Add the memory_limiter processor
processors:
  batch:
  memory_limiter:
    # Set the memory limit to 75% of the container's memory limit
    # For example, if your container has a 1GB limit, set this to 750MiB
    limit_mib: 750
    # How often to check memory usage
    check_interval: 1s

exporters:
  otlp/traces:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
  debug:
    # verbosity: detailed

extensions:
  health_check: {}

service:
  # Enable the extensions
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      # Memory limiter should be the first processor
      processors: [memory_limiter, batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp]
      # Memory limiter should be the first processor
      processors: [memory_limiter, batch]
      exporters: [debug, prometheus]