FROM fluent/fluentd:v1.6-1

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish

USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "3.5.2"]
USER fluent