version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/mnt/ssd/projects/private-hosting/elasticsearch_kibana/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - functions
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"
    volumes:
      - "/mnt/ssd/projects/private-hosting/elasticsearch_kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    networks:
      - functions

networks:
  functions:
    external: true