global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG
  format: json

entryPoints:
  forwardauth:
    address: :4000
    forwardedHeaders:
      insecure: true
  webdbapp:
    address: :27000
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecured
          scheme: https
  websecured:
    address: ":443"
    asDefault: true
  traefik:
    address: ":8080"
  redis-manager:
    address: ":8090"
  minecraft:
    address: ":25000/udp"

accessLog: {}

api:
  insecure: true
  dashboard: true
  debug: true

ping:
  entryPoint: websecured

providers:
  file:
    filename: /traefik_dynamic.yml
    watch: true

  docker:
    defaultRule: Host(`{{ normalize .Name }}`)
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: public-proxy

certificatesResolvers:
  default:
    acme:
      email: asharma.domain@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
