global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG
  format: json

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecured
          scheme: https
  websecured:
    address: ":443"
  traefik:
    address: ":8080"

accessLog: {}

api:
  insecure: true
  dashboard: true
  debug: true

ping:
  entryPoint: websecured

providers:
  file:
    filename: /traefik_dynamic.yml
    watch: true

  docker:
    defaultRule: Host(`{{ normalize .Name }}`)
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    swarmMode: false
    network: public-proxy

certificatesResolvers:
  default:
    acme:
      email: asharma.domain@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
