[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "json"

[entryPoints.http]
  address = ":80"

[entryPoints.https]
  address = ":443"

[entryPoints.traefik]
  address = ":8080"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[accessLog]

[api]
  dashboard = true
  debug = true
  insecure = true

[ping]
  entryPoint = "https"

[retry]

[providers]
  [providers.file]
    watch = true
    filename = "/traefik_dynamic.toml"

  [providers.docker]
    defaultRule = "host.local"
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    swarmMode = true
    network = "functions"

[certificatesResolvers.default.acme]
  email = "asharma.domain@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "http"
