[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "json"

[entryPoints.http]
  address = ":80"

[entryPoints.https]
  address = ":443"

[entryPoints.traefik]
  address = ":8080"

[http.routers]
  [http.routers.api]
    # Matches http://traefik.domain.com/api or http://traefik.domain.com/dashboard
    # but does not match http://traefik.domain.com/hello
    rule = "Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    service = "api@internal"
    entrypoints = ["traefik"]
    middlewares = ["default-auth@file"]

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[accessLog]

[api]
  dashboard = true
  debug = true
  insecure = true

[ping]
  entryPoint = "https"

[retry]

[providers.file]
  watch = true
  filename = "/traefik_dynamic.toml"

[providers.docker]
  defaultRule = "host.local"
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  swarmMode = true
  network = "functions"

[certificatesResolvers.default.acme]
  email = "asharma.domain@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "http"
