
[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"
  [http.middlewares.default-auth.basicAuth]
    usersFile = "/htpasswd.api"
  [http.middlewares.default-compress.compress]
    compress = true