debug = true
# Log level
#
# Optional
# Default: "ERROR"
#
# Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# Messages at and above the selected level will be logged.
#
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8080"
    [entryPoints.api.auth.basic]
    usersFile = "/htpasswd.api"

[api]
entryPoint = "api"
dashboard = true

[ping]
entryPoint = "https"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "offsite.apogee-dev.com"
watch = true
exposedByDefault = false
swarmMode = true

[acme]
email = "asharma.domain@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
  main = "offsite.apogee-dev.com"
[[acme.domains]]
  main = "docker-registry.apogee-dev.com"
[[acme.domains]]
  main = "faas.apogee-dev.com"
[[acme.domains]]
  main = "ryyng.apogee-dev.com"
