version: "3.7"

services:
  registry:
    image: registry:2
    restart: "always"
    ports:
      - "5000"
    deploy:
      labels:
        - "traefik.http.routers.registry.rule=Host(`docker-registry.apogee-dev.com`) && PathPrefix(`/v2`)"
        # per router http to https redirection
        - "traefik.http.routers.registry.entrypoints=http,https"
        - "traefik.http.routers.registry.middlewares=redirect@file,default-auth@file"
        - "traefik.http.routers.registry.service=registry"
        - "traefik.http.routers.registry.tls.domains[0].main=docker-registry.apogee-dev.com"
        - "traefik.http.routers.registry.tls.certResolver=default"

        - "traefik.http.services.registry.loadbalancer.server.port=5000"

        - "traefik.enable=true"
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - "/mnt/ssd/projects/docker-registry/storage:/var/lib/registry"
    networks:
      - functions
    container_name: "docker_registry"

  registry_ui:
    image: joxit/docker-registry-ui:static
    restart: "always"
    environment:
      REGISTRY_URL: "http://registry:5000"
      PULL_URL: "http://registry:5000"
      REGISTRY_TITLE: "Apogee-Dev Private Docker Registry"
      DELETE_IMAGES: "true"
    depends_on: ["registry"]
    deploy:
      labels:
        - "traefik.docker.network=functions"
        - "traefik.enable=true"

        - "traefik.http.routers.registry-ui.rule=Host(`docker-registry.apogee-dev.com`) && PathPrefix(`/ui`)"
        - "traefik.http.routers.registry-ui.entrypoints=http,https"
        - "traefik.http.routers.registry-ui.middlewares=redirect@file,default-auth@file,stripprefix-ui"
        - "traefik.http.routers.registry-ui.service=registry-ui"
        - "traefik.http.routers.registry-ui.tls.domains[0].main=docker-registry.apogee-dev.com"
        - "traefik.http.routers.registry-ui.tls.certResolver=default"

        - "traefik.http.middlewares.stripprefix-ui.stripprefix.prefixes=/ui"

        - "traefik.http.services.registry-ui.loadbalancer.server.port=80"
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - "/mnt/ssd/projects/docker-registry-ui/h2:/var/lib/h2"
    networks:
      - functions
    logging:
      driver: fluentd
      options:
        tag: "docker.{{.Name}}"
        env: "SERVICE_NAME,DEPLOY_ENV"
        fluentd-address: localhost:24224

networks:
  functions:
    external: true
