version: "3.7"

services:
  registry:
    image: registry:2
    restart: "always"
    ports:
      - "5000"
    deploy:
      labels:
        - "traefik.http.routers.registry.rule=Host(`docker-registry.apogee-dev.com`)"
        # per router http to https redirection
        - "traefik.http.routers.registry.entrypoints=http,https"
        - "traefik.http.routers.registry.middlewares=redirect@file,default-auth@file"
        - "traefik.http.routers.registry.service=registry"
        - "traefik.http.routers.registry.tls.domains[0].main=docker-registry.apogee-dev.com"
        - "traefik.http.routers.registry.tls.certResolver=default"

        - "traefik.http.services.registry.loadbalancer.server.port=5000"

        - "traefik.enable=true"
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
     - "/mnt/ssd/projects/docker-registry/storage:/var/lib/registry"
    networks:
      - functions
    container_name: "docker_registry"

  registry_ui:
    image: atcol/docker-registry-ui
    restart: "always"
    environment:
      REG1: "http://registry:5000/v2/"
      READ_ONLY: "true"
    deploy:
      labels:
        - "traefik.docker.network=functions"
        - "traefik.enable=true"
        - "traefik.domain=docker-registry-ui.apogee-dev.com"
        - "traefik.frontend.rule=Host:docker-registry-ui.apogee-dev.com"
        - "traefik.registry.frontend.auth.forward.address=https://offsite.apogee-dev.com/hostmgmt/api/authentication/verify"
        - "traefik.frontend.ratelimit.extractorFunc=client.ip"
        - "traefik.frontend.rateLimit.rateSet.rateset1.period=3"
        - "traefik.frontend.rateLimit.rateSet.rateset1.average=5"
        - "traefik.frontend.rateLimit.rateSet.rateset1.burst=10"
        - "traefik.port=8080"
        - "traefik.protocol=http"
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    # no need to expose ports within a swarm
    #expose:
    #  - "8080"
    volumes:
     - "/mnt/ssd/projects/docker-registry-ui/h2:/var/lib/h2"
    networks:
      - functions
    labels:
      - "traefik.docker.network=functions"
      - "traefik.enable=true"
      - "traefik.domain=docker-registry-ui.apogee-dev.com"
      - "traefik.frontend.rule=Host:docker-registry-ui.apogee-dev.com"
      - "traefik.registry.frontend.auth.forward.address=https://offsite.apogee-dev.com/hostmgmt/api/authentication/verify"
      - "traefik.frontend.ratelimit.extractorFunc=client.ip"
      - "traefik.frontend.rateLimit.rateSet.rateset1.period=3"
      - "traefik.frontend.rateLimit.rateSet.rateset1.average=5"
      - "traefik.frontend.rateLimit.rateSet.rateset1.burst=10"
      - "traefik.port=8080"
      - "traefik.protocol=http"
    container_name: "docker_registry_ui"

networks:
  functions:
    external: true