version: '3.3'
services:
  fluentd:
    image: docker-registry.apogee-dev.com/custom-fluentd
    container_name: fluentd
    environment:
      - FLUENTD_CONF=custom_fluentd.conf
    volumes:
      - "/mnt/ssd/projects/private-hosting/fluentd_elasticsearch_kibana/data:/fluentd/log"
      - "/mnt/ssd/projects/private-hosting/fluentd_elasticsearch_kibana/etc:/fluentd/etc"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - functions
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/mnt/ssd/projects/private-hosting/fluentd_elasticsearch_kibana/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - functions
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      SERVER_NAME: localhost
    ports:
      - "5601:5601"
    volumes:
      - "/mnt/ssd/projects/private-hosting/fluentd_elasticsearch_kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    networks:
      - functions

networks:
  functions:
    external: true