version: "3.3"
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    networks:
      - functions
    logging:
      driver: fluentd
    volumes:
      - "/mnt/ssd/projects/private-hosting/openvpn/openvpn-data/conf:/etc/openvpn"
networks:
  functions:
    external: true