

services:
  webapp:
    image: docker-registry.apogee-dev.com/ryyng:latest
    volumes:
      - "/mnt/ssd/projects/private-hosting/ryyng/config:/home/app/config:ro"
    restart: "always"
    deploy:
      labels:
        - "traefik.docker.network=functions"
        - "traefik.enable=true"
        - "traefik.http.routers.ryyng.rule=Host(`ryyng.apogee-dev.com`)"
        - "traefik.http.routers.ryyng.entrypoints=web,websecured"
        - "traefik.http.routers.ryyng.middlewares=default-compress@file"
        - "traefik.http.routers.ryyng.tls.domains[0].main=ryyng.apogee-dev.com"
        - "traefik.http.routers.ryyng.tls.certResolver=default"
        - "traefik.http.routers.ryyng.service=ryyng"
        - "traefik.http.services.ryyng.loadbalancer.server.port=5000"
      mode: replicated
      placement:
        constraints:
          - "node.platform.os == linux"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - functions
    logging:
      driver: fluentd
      options:
        tag: "docker.{{.Name}}"
        env: "SERVICE_NAME,DEPLOY_ENV"
        fluentd-address: localhost:24224

networks:
  functions:
    external: true
