version: "3.7"
services:
  forwardauth:
    image: apogee-dev/traefik-forward-auth:local
    restart: unless-stopped
    labels:
      - "traefik.docker.network=public-proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.internal-auth.entrypoints=websecured"
      - "traefik.http.routers.internal-auth.rule=Host(`fwd-auth.internal.apogee-dev.com`)"
      - "traefik.http.routers.internal-auth.middlewares=default-compress@file"
      - "traefik.http.routers.internal-auth.service=internal-auth"
      - "traefik.http.routers.internal-auth.tls=true"
      - "traefik.http.routers.internal-auth.tls.domains[0].main=fwd-auth.internal.apogee-dev.com"

      - "traefik.http.services.internal-auth.loadbalancer.server.port=5000"
    volumes:
      - "${HOSTING_DIR}/traefik-forward-auth/dpapi-keys:/dpapi-keys"
    networks:
      - public-proxy
    container_name: webdb-forward-auth
    environment:
      #APP_AppPathPrefix: "/auth"
      App_AppOptions__Username: "${BasicAuthUser}"
      App_AppOptions__Password: "${BasicAuthPassword}"
      APP_AppOptions__MongoDbConnection: "${MongoDbConnection}"
      APP_AppOptions__DatabaseName: "${DatabaseName}"
    logging:
      driver: loki
      options:
        loki-url: "http://proxy.internal.apogee-dev.com:3100/loki/api/v1/push"
        max-size: "100m"

networks:
  public-proxy:
    external: true
