version: "3.7"

services:
  database:
    image: postgres:14.5-alpine
    networks:
      - public-proxy
    volumes:
      - "/mnt/ssd/projects/private-hosting/postgres/storage:/var/lib/postgresql/data"
      - "/mnt/ssd/projects/private-hosting/postgres/secrets:/dbsecrets:ro"
      - "/mnt/ssd/projects/private-hosting/postgres/my-postgres.conf:/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_PASSWORD_FILE: "/dbsecrets/root_password"
      POSTGRES_USER_FILE: "/dbsecrets/user"
    labels:
      - "traefik.enable=true"

  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    networks:
      - public-proxy
    environment:
      PGADMIN_DEFAULT_PASSWORD: ""
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.com"
    volumes:
      - "/mnt/ssd/projects/private-hosting/postgres/secrets:/dbsecrets:ro"

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    networks:
      - public-proxy
    volumes:
      - "/mnt/ssd/projects/private-hosting/postgres/secrets:/dbsecrets:ro"
    environment:
      - PGRST_DB_URI=@/dbsecrets/pgrst_db_uri
      - PGRST_DB_ANON_ROLE=anonymous
      - PGRST_DB_SCHEMA=public,api
      - PGRST_JWT_SECRET=@/dbsecrets/pgrst_jwt_secret
    labels:
      - "traefik.docker.network=public-proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.db-api-1.rule=Host(`db1-f95c49fd.apogee-dev.com`)"
      - "traefik.http.routers.db-api-1.entrypoints=websecured"
      - "traefik.http.routers.db-api-1.tls=true"
      - "traefik.http.routers.db-api-1.tls.domains[0].main=db1-f95c49fd.apogee-dev.com"
      - "traefik.http.routers.db-api-1.tls.certResolver=default"
      - "traefik.http.routers.db-api-1.service=postgres-api"
      - "traefik.http.services.postgres-api.loadbalancer.server.port=3000"

networks:
  public-proxy:
    external: true
