

services:
  database:
    image: postgres:15-alpine
    container_name: pg-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - public-proxy
    volumes:
      - "${HOSTING_DIR}/postgres/storage:/var/lib/postgresql/data"
      - "${HOSTING_DIR}/postgres/secrets:/dbsecrets:ro"
      - "${HOSTING_DIR}/postgres/my-postgres.conf:/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_PASSWORD_FILE: "/dbsecrets/root_password"
      POSTGRES_USER_FILE: "/dbsecrets/user"
    labels:
      - "traefik.enable=true"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    user: 0:0
    restart: unless-stopped
    ports:
      - "5050:80"
    networks:
      - public-proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    volumes:
      - "${HOSTING_DIR}/postgres/secrets:/dbsecrets:ro"
      - "${HOSTING_DIR}/postgres/pgadmin/config:/var/lib/pgadmin"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

networks:
  public-proxy:
    external: true
