

services:
  database:
    image: postgres:15-alpine
    container_name: pg-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - public-proxy
    volumes:
      - "${HOSTING_DIR}/postgres/storage:/var/lib/postgresql/data"
      - "${HOSTING_DIR}/postgres/secrets:/dbsecrets:ro"
      - "${HOSTING_DIR}/postgres/my-postgres.conf:/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_PASSWORD_FILE: "/dbsecrets/root_password"
      POSTGRES_USER_FILE: "/dbsecrets/user"
    labels:
      - "traefik.enable=true"

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    user: 0:0
    restart: unless-stopped
    networks:
      - public-proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "${DefaultPassword}"
    volumes:
      - "${HOSTING_DIR}/postgres/secrets:/dbsecrets:ro"
      - "${HOSTING_DIR}/postgres/pgadmin/config:/var/lib/pgadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-proxy"
      - "traefik.http.routers.pgadmin.entrypoints=websecured"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.internal.apogee-dev.com`)"
      - "traefik.http.routers.pgadmin.middlewares=default-compress@file"
      - "traefik.http.routers.pgadmin.service=pgadmin"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.domains[0].main=pgadmin.internal.apogee-dev.com"

      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

networks:
  public-proxy:
    external: true
